language: c

sudo: false

addons:
  apt:
    packages:
      - libzmq3
      - unixodbc
      - libzmq3-dev
      - unixodbc-dev
      - libsqliteodbc

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    # - LUA=luajit2.0  # current head of 2.0 branch
    # - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install lzmq
  - luarocks install odbc
  - luarocks install luq
  - luarocks install lua-llthreads2

install:
  - luarocks make rockspecs/odbc-pool-scm-0.rockspec

script:
  - cd test
  - lua test_pool.lua
  - lua bench_pool.lua

notifications:
  email:
    on_success: change
    on_failure: always
